import type { LucideIcon } from "lucide-react";
import {
  BedDouble,
  Boxes,
  Building2,
  Calculator,
  Cable,
  ClipboardCheck,
  ClipboardList,
  Database,
  FileText,
  HardHat,
  Headphones,
  Landmark,
  LifeBuoy,
  Monitor,
  Network,
  Package,
  Rocket,
  Scale,
  Search,
  Send,
  Server,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Stethoscope,
  School,
  Store,
  Briefcase,
  TrendingUp,
  Users,
  Workflow,
} from "lucide-react";

const registry: Record<string, LucideIcon> = {
  bedDouble: BedDouble,
  boxes: Boxes,
  briefcase: Briefcase,
  building2: Building2,
  calculator: Calculator,
  cable: Cable,
  clipboardCheck: ClipboardCheck,
  clipboardList: ClipboardList,
  database: Database,
  fileText: FileText,
  hardHat: HardHat,
  headphones: Headphones,
  landmark: Landmark,
  lifeBuoy: LifeBuoy,
  monitor: Monitor,
  network: Network,
  package: Package,
  rocket: Rocket,
  scale: Scale,
  school: School,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  shieldCheck: ShieldCheck,
  shoppingCart: ShoppingCart,
  stethoscope: Stethoscope,
  store: Store,
  trendingUp: TrendingUp,
  users: Users,
  workflow: Workflow,
};

export function getIcon(name: string): LucideIcon {
  return registry[name] ?? FileText;
}
